import Link from 'next/link'
import Layout from '../components/Layout.js'

export default function Articles({
  articles
}) {
  return (
    <Layout
      title="Articles"
      description="Generated by create next app"
      >
    <h1 className='text-center text-4xl font-bold mt-8 mb-4'>
  Web Technologies Articles
</h1>
<div className="my-5">
        <Link href="/create-article">
          <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            Create New Article
          </button>
        </Link>
      </div>
      <p className="italic font-bold my-5">This page fetches data at build time, excellent for SEO.</p>
      {/* <ul>
        {articles.map( article => (
          <li key={article.slug} className="my-5">
            <h2 className="font-bold mb-1">
              <Link href={`/articles/${article.slug}`}>{article.title}</Link>
            </h2>
            <p>{article.message}</p>
          </li>
        ))}
      </ul> */}

{/* new style */}
<div className='flex'>
{articles.map( article => (
      <div  key={article.slug} class=" max-w-sm rounded overflow-hidden shadow-lg">
  <div class="px-6 py-4">
    <div class="text-center font-bold text-xl mb-2"><Link href={`/articles/${article.slug}`}>{article.title}</Link></div>
    <p class="text-gray-700 text-base">
        {article.message}
    </p>
  </div>
 
</div>
 ))}
  </div>
    </Layout>
  )
}

export async function getStaticProps(ctx) {
  const response = await fetch(`http://localhost:3000/api/articles`)
  const articles = await response.json()
  return {
    props: {
      articles: articles
    }
  }
}