import Head from 'next/head';
import { useState } from 'react';
import { useSupabaseClient } from '@supabase/auth-helpers-react';
import Layout from '../components/Layout.js';

export default function Page() {
  const supabase = useSupabaseClient()
  const [message, setMessage] = useState(null)
  const onSubmit = async function(e){
    e.preventDefault()
    // Insert contact record into the contacts database
    // Print a friendly confirmation message
  }
  return (
    <Layout>
      <Head>
        <title>WebTech - contact us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='wt-title'>
        Contact
      </h1>
      <form className="[&_span]:block" onSubmit={onSubmit}>
        <div>
          <label>
            <span>First name</span>
            <input type="text" name="firstname" />
          </label>
        </div>
        <div>
          <label>
            <span>Last name</span>
            <input type="text" name="lastname" />
          </label>
        </div>
        <div>
          <label>
            <span>Email</span>
            <input type="text" name="email" />
          </label>
        </div>
        <div>
          <label>
            <span>Message</span>
            <textarea name="message" />
          </label>
        </div>
        <div>
          <input type="submit" value="Send" />
        </div>
      </form>
      {message &&
        <div
          aria-label="Alert pane"
          className="fixed inset-0 bg-black/80 flex items-center justify-center"
          onClick={() => setMessage(null)}
          role="dialog"
        >
          <div
            aria-label="Alert message"
            className="max-h-[90vh] max-w-[95vw] overflow-auto p-4 prose bg-white"
          >
            {message}
          </div>
        </div>
      }
    </Layout>
  );
}