import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/Layout.js'
import { useContext } from 'react';
import UserContext from '../components/UserContext'

export default function Page() {
  const {profile} = useContext(UserContext)
  return (
    <Layout
    
      title=""
      description="Generated by create next app"
      >

      {/* {profile && (
        
        <div>
          {profile.username},
        </div>
      )} */}
  

      <h1 className='text-center text-4xl font-bold mt-8 mb-4'>
          Welcome to <a href="https://www.adaltas.com">web technologies!</a>
     </h1>

     <div className='text-center text-4xl font-bold mt-8 mb-4'>
        <button class="text-center bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">
        <Link href="/articles">
            View our articles
          </Link>
        </button>
     </div>

     <div class="flex mb-4">
<div className="w-1/3  h-12 flex items-center">
  <button className="ml-auto bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">
    <Link href="/about">
      About us
    </Link>
  </button>
</div>

  <div class="w-1/3 h-12"></div>
  <div class="w-1/3  h-12">
              <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">
               <Link href="/contacts">
                   Contact us
                </Link>
            </button>
  </div>
</div>
    </Layout>
  )
}